"""empty message

Revision ID: 2dbc550d0740
Revises: 5d280ac861ba
Create Date: 2019-05-20 23:00:39.022595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2dbc550d0740'
down_revision = '5d280ac861ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('history_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('time', sa.String(length=80), nullable=True),
    sa.Column('xcords', sa.String(length=80), nullable=True),
    sa.Column('ycords', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('devicename', sa.String(length=80), nullable=True),
    sa.Column('macaddress', sa.String(length=80), nullable=True),
    sa.Column('userid', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_devices')
    op.drop_table('history_data')
    # ### end Alembic commands ###
