"""empty message

Revision ID: 32f7fd8ac173
Revises: 49ef07a54108
Create Date: 2019-05-21 02:44:58.033292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32f7fd8ac173'
down_revision = '49ef07a54108'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_data', sa.Column('percentage', sa.String(length=80), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('app_data', 'percentage')
    # ### end Alembic commands ###
