"""empty message

Revision ID: 342932dbbcc2
Revises: 8dd159c23fbe
Create Date: 2019-05-21 01:29:25.914504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '342932dbbcc2'
down_revision = '8dd159c23fbe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_devices', sa.Column('lat', sa.Integer(), nullable=True))
    op.add_column('user_devices', sa.Column('longg', sa.Integer(), nullable=True))
    op.drop_column('user_devices', 'userid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_devices', sa.Column('userid', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('user_devices', 'longg')
    op.drop_column('user_devices', 'lat')
    # ### end Alembic commands ###
