"""empty message

Revision ID: 49ef07a54108
Revises: 90244d9685da
Create Date: 2019-05-21 02:42:35.130070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49ef07a54108'
down_revision = '90244d9685da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_data', sa.Column('macaddress', sa.String(length=80), nullable=True))
    op.add_column('app_data', sa.Column('rssi', sa.String(length=80), nullable=True))
    op.drop_column('app_data', 'RSSI')
    op.drop_column('app_data', 'MAC')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_data', sa.Column('MAC', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    op.add_column('app_data', sa.Column('RSSI', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    op.drop_column('app_data', 'rssi')
    op.drop_column('app_data', 'macaddress')
    # ### end Alembic commands ###
