"""empty message

Revision ID: 4ab8b27999d4
Revises: de43c846819e
Create Date: 2019-05-21 03:01:03.804619

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4ab8b27999d4'
down_revision = 'de43c846819e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_datad',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('macaddress', sa.String(length=80), nullable=True),
    sa.Column('distance', sa.Float(), nullable=True),
    sa.Column('frequency', sa.Integer(), nullable=True),
    sa.Column('rssi', sa.Integer(), nullable=True),
    sa.Column('scantime', sa.String(length=80), nullable=True),
    sa.Column('percentage', sa.Float(precision=1), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('app_data')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_data',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('macaddress', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('distance', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('frequency', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('rssi', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('scantime', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('percentage', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=u'app_data_pkey')
    )
    op.drop_table('app_datad')
    # ### end Alembic commands ###
