"""empty message

Revision ID: 4b48c5ed00e0
Revises: 342932dbbcc2
Create Date: 2019-05-21 01:53:36.714714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b48c5ed00e0'
down_revision = '342932dbbcc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_devicess',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('devicename', sa.String(length=80), nullable=True),
    sa.Column('macaddress', sa.String(length=80), nullable=True),
    sa.Column('longg', sa.Float(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('user_devices')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_devices',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('devicename', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('macaddress', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('lat', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('longg', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=u'user_devices_pkey')
    )
    op.drop_table('user_devicess')
    # ### end Alembic commands ###
