"""empty message

Revision ID: 5914763297a2
Revises: f146c18c6f3a
Create Date: 2019-05-20 18:37:54.107880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5914763297a2'
down_revision = 'f146c18c6f3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ap_data', 'percentage')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ap_data', sa.Column('percentage', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
