"""empty message

Revision ID: 5d280ac861ba
Revises: 5914763297a2
Create Date: 2019-05-20 18:44:27.691036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d280ac861ba'
down_revision = '5914763297a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('MAC', sa.String(length=80), nullable=True),
    sa.Column('distance', sa.String(length=80), nullable=True),
    sa.Column('frequency', sa.String(length=80), nullable=True),
    sa.Column('RSSI', sa.String(length=80), nullable=True),
    sa.Column('scantime', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('ap_data')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ap_data',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('MAC', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('distance', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('frequency', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('RSSI', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('scantime', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=u'ap_data_pkey')
    )
    op.drop_table('app_data')
    # ### end Alembic commands ###
