"""empty message

Revision ID: 829a0a8d1836
Revises: ef3741637848
Create Date: 2019-05-21 06:19:17.624667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '829a0a8d1836'
down_revision = 'ef3741637848'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_data', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.add_column('history_data', sa.Column('datetime', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('history_data', 'datetime')
    op.drop_column('app_data', 'timestamp')
    # ### end Alembic commands ###
