"""empty message

Revision ID: 8dd159c23fbe
Revises: 2dbc550d0740
Create Date: 2019-05-21 00:55:01.377771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8dd159c23fbe'
down_revision = '2dbc550d0740'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('password', sa.String(length=255), nullable=True))
    op.drop_constraint(u'user_profiles_email_key', 'user_profiles', type_='unique')
    op.drop_constraint(u'user_profiles_passwordHash_key', 'user_profiles', type_='unique')
    op.drop_column('user_profiles', 'passwordHash')
    op.drop_column('user_profiles', 'salt')
    op.drop_column('user_profiles', 'email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('email', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    op.add_column('user_profiles', sa.Column('salt', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    op.add_column('user_profiles', sa.Column('passwordHash', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    op.create_unique_constraint(u'user_profiles_passwordHash_key', 'user_profiles', ['passwordHash'])
    op.create_unique_constraint(u'user_profiles_email_key', 'user_profiles', ['email'])
    op.drop_column('user_profiles', 'password')
    # ### end Alembic commands ###
