"""empty message

Revision ID: 90244d9685da
Revises: 4b48c5ed00e0
Create Date: 2019-05-21 01:53:59.092441

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '90244d9685da'
down_revision = '4b48c5ed00e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('devicename', sa.String(length=80), nullable=True),
    sa.Column('macaddress', sa.String(length=80), nullable=True),
    sa.Column('longg', sa.Float(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('user_devicess')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_devicess',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('devicename', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('macaddress', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('longg', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('lat', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=u'user_devicess_pkey')
    )
    op.drop_table('user_devices')
    # ### end Alembic commands ###
