"""empty message

Revision ID: e4b72c7da41a
Revises: ab50f9771c25
Create Date: 2019-05-21 04:15:57.735799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4b72c7da41a'
down_revision = 'ab50f9771c25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_data', sa.Column('datetime', sa.DateTime(), nullable=True))
    op.drop_column('test_data', 'data')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_data', sa.Column('data', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    op.drop_column('test_data', 'datetime')
    # ### end Alembic commands ###
