"""empty message

Revision ID: ef3741637848
Revises: faba7684590c
Create Date: 2019-05-21 04:40:19.393938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef3741637848'
down_revision = 'faba7684590c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_dataa', sa.Column('data', sa.Integer(), nullable=True))
    op.drop_column('test_dataa', 'test')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_dataa', sa.Column('test', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('test_dataa', 'data')
    # ### end Alembic commands ###
