"""empty message

Revision ID: f146c18c6f3a
Revises: 505ae8f295d9
Create Date: 2019-05-20 18:28:10.192210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f146c18c6f3a'
down_revision = '505ae8f295d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ap_data', sa.Column('scantime', sa.String(length=80), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ap_data', 'scantime')
    # ### end Alembic commands ###
