"""empty message

Revision ID: faba7684590c
Revises: 06121a1ae669
Create Date: 2019-05-21 04:27:33.002955

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'faba7684590c'
down_revision = '06121a1ae669'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_dataa', sa.Column('test', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_dataa', 'test')
    # ### end Alembic commands ###
